<%@ Page Language="C#" AutoEventWireup="true" CodeFile="DynameicWriteSQL.aspx.cs" Inherits="DynameicWriteSQL" %>

<%@ Register assembly="CrystalDecisions.Web, Version=13.0.2000.0, Culture=neutral, PublicKeyToken=692fbea5521e1304" namespace="CrystalDecisions.Web" tagprefix="CR" %>
<%@ Register assembly="Microsoft.ReportViewer.WebForms, Version=12.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91" namespace="Microsoft.Reporting.WebForms" tagprefix="rsweb" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link rel="stylesheet" type="text/css" media="print" href="./Content/print.css" />
    <link rel="stylesheet" type="text/css" href="./Content/reset_MySet.css" />
    <link rel="stylesheet" type="text/css" href="./Content/table.css" />
    <title>進貨管理-建立進貨憑單</title>
</head>
<script>
    function ShowREV() {
        //alert(document.getElementById("MyName").value);
        if (this.value == '') {
            //document.getElementById("txtMsg").innerText = '不能為空';
            //onblur="if(this.value==''){alert('不能空白');this.focus();}"
            alert('不可為空');
            this.focus();
        }
    }
</script>
    <!--
    <script  type = "text/javascript" > 
        function clickEnter(obj, event)
        {
            var keyCode; 
            if (event.keyCode > 0)
            {
                keyCode = event.keyCode;
            }
            else if (event.which > 0)
            {
                keyCode = event.which;
            }
            else
            {
                keycode = event.charCode;
            }
            if (keyCode == 13)
            {
                document.getElementById ( obj ).focus(); 
                return  false ; 
            } 
            else
            {
                return  true ; 
            } 
        } 
    </script>
        -->
<body>

    <form id="form1" runat="server" method="post">
        <div class="noprint" style="z-index: 999; position: fixed; width: 269px; top: 15px; left: 10px;">
            <asp:TreeView ID="IM_TreeView" runat="server" DataSourceID="IM_XmlDataSource" ImageSet="Simple" BackColor="#CCCCCC" BorderColor="#999999" BorderStyle="Outset" ExpandDepth="2" Font-Bold="True" Font-Names="微軟正黑體" Font-Size="Large" AutoGenerateDataBindings="False" Width="227px" ForeColor="White" Style="background-color: #333333">
                <DataBindings>
                    <asp:TreeNodeBinding DataMember="Root" TextField="name" ValueField="describe" NavigateUrlField="url" />
                    <asp:TreeNodeBinding DataMember="Parent" TextField="name" SelectAction="None" />
                    <asp:TreeNodeBinding DataMember="Child" TextField="name" ValueField="name" NavigateUrlField="url" />
                </DataBindings>
                <HoverNodeStyle Font-Underline="True" ForeColor="#5555DD" />
                <LeafNodeStyle ChildNodesPadding="10px" />
                <NodeStyle Font-Names="微軟正黑體" Font-Size="Large" ForeColor="White" HorizontalPadding="0px" NodeSpacing="2px" VerticalPadding="0px" Font-Bold="False" />
                <ParentNodeStyle Font-Bold="True" ChildNodesPadding="10px" />
                <RootNodeStyle ChildNodesPadding="5px" Font-Bold="False" />
                <SelectedNodeStyle Font-Underline="True" ForeColor="#5555DD" HorizontalPadding="0px" VerticalPadding="0px" Font-Bold="True" Font-Names="微軟正黑體" Font-Size="X-Large" />
            </asp:TreeView>
            <asp:XmlDataSource ID="IM_XmlDataSource" runat="server" DataFile="~/InventoryManagement.xml"></asp:XmlDataSource>
        </div>

        <div style="position: relative; margin: 0 auto; text-align: center; width: 21cm; height: 11cm; top: 15px; left: 0px;" />
        <!--Title-->
        <div class="noprint">
            <asp:Label CssClass="noprint" ID="Label2" runat="server" Font-Bold="True" Font-Names="微軟正黑體" Font-Size="XX-Large" Text="進貨管理-建立進貨憑單"></asp:Label>
        </div>
        <!--Content-->
        <div id="myBMnoprint" class="noprint" runat="server" style="display: block; line-height: 24px; text-align: center; height: 303px;">
            <asp:Label ID="Label3" runat="server" Font-Bold="True" Font-Names="微軟正黑體" Font-Size="Large" ForeColor="Black" Style="text-align: center" Font-Underline="True">進貨單資料</asp:Label>
            <br />
            <div style="text-align: center;">
                進貨單號：<asp:Label ID="txt_id" runat="server" Font-Bold="True" Font-Names="微軟正黑體" Font-Size="Medium" ForeColor="Black" Style="text-align: left" Font-Underline="True"></asp:Label>
                &nbsp;
                    進貨日期：<asp:Label ID="txt_CreateTime" runat="server" Font-Bold="True" Font-Names="微軟正黑體" Font-Size="Medium" ForeColor="Black" Style="text-align: left" Font-Underline="True"></asp:Label>
                <br />
                <br />
            </div>
            <!--Customer-->
            <div class="noprint" style="font-size: 30px; font-weight: bold; text-align: left;">客戶</div>
            <div style="border: 3px solid rgba(200,200,200,0.4); padding: 3px; font-weight: bold; line-height: 30px; float: left; display: block; text-align: left; width: 21cm;">
                <asp:Button ID="SelectCustomer" runat="server" Text="選擇客戶" Width="90px" UseSubmitBehavior="False" OnClientClick="window.open('Subwindow_BM.aspx','選擇客戶','menubar=no,status=no,scrollbars=yes,top=100,left=200,toolbar=no,width=800,height=600');return false;" />
                <br />
                客戶編號：<asp:TextBox ID="BM_Id" runat="server" Font-Bold="False" Font-Names="微軟正黑體" Font-Size="17px" ForeColor="Black" Style="text-align: left" Font-Underline="False" Width="150px"></asp:TextBox>
                客戶名稱：<asp:TextBox ID="BM_Name" runat="server" Font-Bold="False" Font-Names="微軟正黑體" Font-Size="17px" ForeColor="Black" Style="text-align: left" Font-Underline="False" Width="150px"></asp:TextBox>
                <br />
                客戶電話：<asp:TextBox ID="BM_Tel" runat="server" Font-Bold="False" Font-Names="微軟正黑體" Font-Size="17px" ForeColor="Black" Style="text-align: left" Font-Underline="False" Width="150px"></asp:TextBox>
                客戶手機：<asp:TextBox ID="BM_cell" runat="server" Font-Bold="False" Font-Names="微軟正黑體" Font-Size="17px" ForeColor="Black" Style="text-align: left" Font-Underline="False" Width="150px"></asp:TextBox>
                客戶傳真：<asp:TextBox ID="BM_Fax" runat="server" Font-Bold="False" Font-Names="微軟正黑體" Font-Size="17px" ForeColor="Black" Style="text-align: left" Font-Underline="False" Width="150px"></asp:TextBox>
                <br />
                客戶備註：<asp:TextBox ID="BM_remark" runat="server" Font-Bold="False" Font-Names="微軟正黑體" Font-Size="17px" ForeColor="Black" Style="text-align: left" Font-Underline="False" Width="340px"></asp:TextBox>
                <br />
                客戶地址：<asp:TextBox ID="BM_address" runat="server" Font-Bold="False" Font-Names="微軟正黑體" Font-Size="17px" ForeColor="Black" Style="text-align: left" Font-Underline="False" Width="340px"></asp:TextBox>
            </div>
        </div>


        <div id="myIMnoprint" class="noprint" runat="server" style="display: block; font-weight: bold; line-height: 24px; text-align: center;">
            <!--Product-->
            <div class="noprint" style="font-size: 30px; font-weight: bold; text-align: left;">產品列表</div>
            <div style="border: 3px solid rgba(200,200,200,0.4); padding: 3px; line-height: 30px; float: left; display: block; text-align: center; width: 21cm;">
                <!--ADD to List Button-->

                <div class="noprint" style="margin: 0 auto">
                    <asp:Button ID="listAddbtn" runat="server" Text="新增" OnClick="listAddbtn_Click" />
                    &nbsp;
                    <asp:Button ID="savebtn" runat="server" Text="儲存" OnClick="savebtn_Click" UseSubmitBehavior="False" />
                    &nbsp;
                    <asp:Button ID="delbtn" runat="server" Text="捨棄" OnClick="delbtn_Click" UseSubmitBehavior="False" />
                    &nbsp;
                    <asp:Button ID="nextbtn" runat="server" Text="下一筆" OnClick="nextbtn_Click" UseSubmitBehavior="False" />
                &nbsp;&nbsp;<asp:Button ID="Button2" runat="server" OnClick="Button2_Click" Text="display" />
                </div>
                <!--List Content-->
                <div id="ListContent" class="noprint" runat="server" style="display: block;">

                    

                    <asp:GridView ID="Gridview1" runat="server" AutoGenerateColumns="False" HorizontalAlign="Center" Width="21cm" OnRowDataBound="Gridview1_RowDataBound" BorderStyle="None" GridLines="Horizontal" OnRowDeleting="Gridview1_RowDeleting" DataKeyNames="Id" EmptyDataText="尚未新增">
                        <Columns>
                            <asp:TemplateField ShowHeader="False">
                                <ItemTemplate>
                                    <asp:Button ID="Delete" runat="server" CausesValidation="False" CommandName="Delete" Text="刪除" OnClientClick="return confirm('確認要刪除嗎？');" />
                                </ItemTemplate>
                            </asp:TemplateField>

                            <asp:TemplateField HeaderText="型號">
                                <ItemTemplate>
                                    <asp:Label ID="ID" runat="server" Text='<%# Bind("Id") %>'></asp:Label>
                                    &nbsp;<asp:TextBox ID="Model" runat="server" Text='<%# Bind("Model") %>' Width="1.5cm" CausesValidation="True" AutoPostBack="True" OnTextChanged="Model_TextChanged" TabIndex="1"></asp:TextBox>
                                    &nbsp;<asp:Button ID="Findbtn" runat="server" CommandName="Find" OnClientClick="window.open('Subwindow_IM.aspx?id={0}&amp;storage={1}&amp;color={2}&amp;weight={3}&amp;price={4}', '選擇產品', 'scrollbars=yes,top=100,left=200,width=800,height=600'); return false;" Text="查詢" Width="1cm" UseSubmitBehavior="False" />
                                </ItemTemplate>
                            </asp:TemplateField>

                            <asp:TemplateField HeaderText="庫存量">
                                <ItemTemplate>
                                    <asp:TextBox ID="StorageNum" runat="server" Enabled="False" Text='<%# Bind("StorageNum") %>' Width="1.5cm"></asp:TextBox>
                                </ItemTemplate>
                            </asp:TemplateField>

                            <asp:TemplateField HeaderText="顏色">
                                <ItemTemplate>
                                    <asp:TextBox ID="Color" runat="server" Text='<%# Bind("Color") %>' Width="1.5cm" AutoPostBack="True" OnTextChanged="Color_TextChanged" TabIndex="2"></asp:TextBox>
                                    &nbsp;<asp:Button ID="Findcolor" runat="server" OnClientClick="window.open('SelectColor.aspx','選擇產品','menubar=no,status=no,scrollbars=yes,top=100,left=200,toolbar=no,width=800,height=600');return false;" Text="查詢" />
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="規格">
                                <ItemTemplate>
                                    <asp:TextBox ID="Lenght" runat="server" Text='<%# Bind("Lenght") %>' Width="1.5cm"></asp:TextBox>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="重量">
                                <ItemTemplate>
                                    <asp:TextBox ID="Weight" runat="server" Text='<%# Bind("Weight") %>' Width="1.5cm"></asp:TextBox>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="數量">
                                <ItemTemplate>
                                    <asp:TextBox ID="Number" runat="server" Text='<%# Bind("Number") %>' Width="1.5cm" AutoPostBack="True" OnTextChanged="Number_TextChanged"></asp:TextBox>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="單價">
                                <ItemTemplate>
                                    <asp:TextBox ID="Price" runat="server" Text='<%# Bind("Price") %>' Width="1.5cm" AutoPostBack="True" OnTextChanged="Price_TextChanged"></asp:TextBox>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="總價">
                                <ItemTemplate>
                                    <asp:Label ID="Total" runat="server" Text='<%# Bind("Total") %>' Width="1.5cm" Font-Size="Small"></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                        </Columns>
                        <RowStyle BorderStyle="None" />
                    </asp:GridView>

                    <script type="text/javascript">
                        function SelectAllCheckboxes(spanChk) {
                            elm = document.forms[0];
                            for (i = 0; i <= elm.length - 1; i++) {
                                if (elm[i].type == "checkbox" && elm[i].id != spanChk.id) {
                                    if (elm.elements[i].checked != spanChk.checked) {
                                        elm.elements[i].click();
                                    }
                                }
                            }
                        }
                    </script>
                </div>
            </div>
        </div>


        <!--Check & Modify & Print Button-->
        <div class="noprint">
            <asp:Button CssClass="noprint" ID="modify" runat="server" OnClick="modify_Click" Text="表單修改" />
            &nbsp;<asp:Button CssClass="noprint" ID="printOK" runat="server" OnClick="printOK_Click" Text="預覽列印" OnClientClick="javascript:window.print()" />
            <br />
            <asp:GridView ID="GV_Display" runat="server">
            </asp:GridView>
        </div>

        <!--Directions-->
        <asp:Label CssClass="noprint" ID="txtMsg" runat="server" Font-Bold="True" Font-Names="微軟正黑體" Font-Size="Large" ForeColor="Red" Style="text-align: left"></asp:Label>
        <!--Print Content-->
        
        <div id="myBMprint" class="print" runat="server" style="position: relative; line-height: 20px; margin: 0; display: block; height: 11cm; text-align: center; top: 0px; left: 0px;">
            <!--
            <asp:Label ID="titletxt" runat="server" Font-Bold="True" Font-Names="微軟正黑體" Font-Size="X-Large" ForeColor="Black" Style="text-align: center">宜昌鋁業有限公司</asp:Label>
            <br />
            <br />
            <asp:Label ID="titletxt0" runat="server" Font-Bold="False" Font-Names="微軟正黑體" Font-Size="Large" ForeColor="Black" Style="text-align: center" Font-Underline="True">進貨單</asp:Label>
            <div style="float: left;">進貨單號:<asp:Label ID="txt_id_print" runat="server" Font-Names="微軟正黑體" ForeColor="Black" Style="text-align: left" Font-Bold="True"></asp:Label></div>
            <div style="float: right;">進貨日期:<asp:Label ID="txt_CreateTime_print" runat="server" Font-Names="微軟正黑體" ForeColor="Black" Style="text-align: left" Font-Bold="True"></asp:Label></div>
            <div class="css_table" style="border-top: 2px solid rgba(130,130,130,0.8)">
                <div class="css_tr">
                    <div class="css_td" style="width: 9cm; text-align: left">
                        客戶名稱:<asp:Label ID="txt_cid_print" runat="server" Font-Names="微軟正黑體" ForeColor="Black" Style="text-align: left"></asp:Label>
                        <asp:Label ID="txt_name_print" runat="server" Font-Names="微軟正黑體" ForeColor="Black" Style="text-align: left"></asp:Label>
                    </div>
                    <div class="css_td" style="width: 6cm; text-align: left">
                        客戶電話:<asp:Label ID="txt_Tel_print" runat="server" Font-Names="微軟正黑體" ForeColor="Black" Style="text-align: left"></asp:Label>
                    </div>
                    <div class="css_td" style="width: 6cm; text-align: left">
                        客戶手機:<asp:Label ID="txt_cell_print" runat="server" Font-Names="微軟正黑體" ForeColor="Black" Style="text-align: left"></asp:Label>
                    </div>
                </div>

                <div class="css_tr">
                    <div class="css_td" style="width: 10cm; text-align: left">
                        客戶地址:<asp:Label ID="txt_addr_print" runat="server" Font-Names="微軟正黑體" ForeColor="Black" Style="text-align: left"></asp:Label>
                    </div>
                    <div class="css_td" style="width: 5cm; text-align: left">
                        客戶傳真:<asp:Label ID="txt_FAX_print" runat="server" Font-Names="微軟正黑體" ForeColor="Black" Style="text-align: left"></asp:Label>
                    </div>
                    <div class="css_td" style="width: 6cm; text-align: left">
                        客戶備註:<asp:Label ID="txt_remark_print" runat="server" Font-Names="微軟正黑體" ForeColor="Black" Style="text-align: left"></asp:Label>
                    </div>
                </div>

            </div>

            <div style="border: 1px solid #000000"></div>
            <asp:GridView ID="Gridview_print" runat="server" AutoGenerateColumns="False" HorizontalAlign="Center" Width="21cm" BorderStyle="None" GridLines="None" EmptyDataText="Error">
                <AlternatingRowStyle BorderStyle="None" />
                <Columns>

                    <asp:TemplateField HeaderText="型號">
                        <ItemTemplate>
                            <asp:Label ID="Model0" runat="server" Text='<%# Bind("p_pmodel") %>' Width="1.5cm"></asp:Label>
                            &nbsp;&nbsp;
                        </ItemTemplate>
                    </asp:TemplateField>

                    <asp:TemplateField HeaderText="擠型">
                        <ItemTemplate>
                            <asp:Image ID="Image1" runat="server" ImageUrl='<%# Eval("p_pimage") %>' />
                        </ItemTemplate>
                    </asp:TemplateField>

                    <asp:TemplateField HeaderText="顏色">
                        <ItemTemplate>
                            <asp:Label ID="Color0" runat="server" Text='<%# Bind("p_pcolor") %>' Width="1.5cm"></asp:Label>
                            &nbsp;&nbsp;
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="規格">
                        <ItemTemplate>
                            <asp:Label ID="Lenght0" runat="server" Text='<%# Bind("p_plen") %>' Width="1.5cm"></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="重量">
                        <ItemTemplate>
                            <asp:Label ID="Weight0" runat="server" Text='<%# Bind("p_pweight") %>' Width="1.5cm"></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="數量">
                        <ItemTemplate>
                            <asp:Label ID="Number0" runat="server" Text='<%# Bind("p_pnum") %>' Width="1.5cm"></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="單價">
                        <ItemTemplate>
                            <asp:Label ID="Price0" runat="server" Text='<%# Bind("p_pprice") %>' Width="1.5cm"></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                </Columns>
                <RowStyle BorderStyle="None" HorizontalAlign="Center" VerticalAlign="Middle" />
            </asp:GridView>
            <div style="float:right">
            </div>
            <div style="float:left">
            </div>
            <br />
            -->
            <div class="print" runat="server">
                <asp:Panel ID="Documents_PD" runat="server" Width="21cm">
                </asp:Panel>


            </div>

        </div>
        
    </form>
</body>
</html>
